### ISSUE TITLE
[BUG] Wrong dependency ordering when having more then 33 injections

### ISSUE THREAD

**Issue by Jozott00** [Milad-Akarie/injectable#330]
In our app we currently have 33 injections that are working perfectly fine. Today I tried to add some more dependencies, which leads to a wrong order of injections. After some debugging, I found that only one more injection was needed to get these wrong results. This injection does not even need a dependency or need to be a dependency of another injection. 

<details>
<summary>Right GetIt injections with less then 34 injections. Note that  both (environment dependent) AppConfig s are correctly added first.</summary>

```dart
const String _dev = 'dev';
const String _prod = 'prod';

/// ignore_for_file: unnecessary_lambdas
/// ignore_for_file: lines_longer_than_80_chars
extension GetItInjectableX on _i1.GetIt {
  /// initializes the registration of main-scope dependencies inside of [GetIt]
  Future<_i1.GetIt> init({
    String? environment,
    _i2.EnvironmentFilter? environmentFilter,
  }) async {
    final gh = _i2.GetItHelper(
      this,
      environment,
      environmentFilter,
    );
    final registerConfiguration = _$RegisterConfiguration();
    final registerModules = _$RegisterModules();
    await gh.singletonAsync<_i3.AppConfig>(
      () => registerConfiguration.appDevConfig,
      registerFor: {_dev},
      preResolve: true,
    );
    await gh.singletonAsync<_i3.AppConfig>(
      () => registerConfiguration.appProdConfig,
      registerFor: {_prod},
      preResolve: true,
    );
    gh.lazySingleton<_i4.AppLinks>(() => registerModules.appLinks);
    gh.lazySingleton<_i5.AuthenticationClient>(
        () => _i6.AuthenticationClientImpl());
    gh.lazySingleton<_i7.GetAuthenticationStatusStream>(() =>
        _i7.GetAuthenticationStatusStream(
            authenticationClient: gh<_i5.AuthenticationClient>()));
    gh.lazySingleton<_i8.GetToken>(() =>
        _i8.GetToken(authorizationClient: gh<_i5.AuthenticationClient>()));
    gh.factory<_i9.LoginCubit>(
        () => _i9.LoginCubit(getToken: gh<_i8.GetToken>()));
    gh.singleton<_i10.QueryExecutor>(
        registerModules.dbExecutor(gh<_i3.AppConfig>()));
    await gh.singletonAsync<_i11.SharedPreferences>(
      () => registerModules.prefs,
      preResolve: true,
    );
    gh.lazySingleton<_i12.StandalonePlaceholder>(
        () => _i12.StandalonePlaceholder());
    gh.lazySingleton<_i13.UserRepository>(() => _i14.UserRepositoryImpl());
    gh.lazySingleton<_i15.GetUser>(
        () => _i15.GetUser(userRepository: gh<_i13.UserRepository>()));
    gh.singleton<_i16.PmDriftDatabase>(
        _i16.PmDriftDatabase(gh<_i10.QueryExecutor>())..initStorageInspector());
    gh.lazySingleton<_i17.PreferenceLocalDataSource>(
        () => _i17.PreferenceLocalDataSourceImpl(gh<_i11.SharedPreferences>()));
    await gh.lazySingletonAsync<_i18.PreferenceRepository>(
      () {
        final i =
            _i19.PreferenceRepositoryImpl(gh<_i17.PreferenceLocalDataSource>());
        return i.demoDefaultListInit().then((_) => i);
      },
      preResolve: true,
      dispose: (i) => i.dispose(),
    );
    gh.lazySingleton<_i20.SetCurrentPacklistId>(
        () => _i20.SetCurrentPacklistId(gh<_i18.PreferenceRepository>()));
    gh.factory<_i21.AuthenticationCubit>(() => _i21.AuthenticationCubit(
          gh<_i7.GetAuthenticationStatusStream>(),
          gh<_i15.GetUser>(),
        ));
    gh.lazySingleton<_i22.GetCurrentPacklistIdStream>(
        () => _i22.GetCurrentPacklistIdStream(gh<_i18.PreferenceRepository>()));
    gh.lazySingleton<_i12.PacklistLocalDao>(
        () => _i12.PacklistLocalDao(gh<_i16.PmDriftDatabase>()));
    gh.lazySingleton<_i23.PacklistRepository>(
        () => _i24.PacklistRepositoryImpl(gh<_i12.PacklistLocalDao>()));
    gh.lazySingleton<_i25.SearchItemByName>(
        () => _i25.SearchItemByName(gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i26.StoreListItem>(() =>
        _i26.StoreListItem(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i27.CreatePacklist>(() =>
        _i27.CreatePacklist(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.factory<_i28.CurrentListCubit>(
        () => _i28.CurrentListCubit(gh<_i22.GetCurrentPacklistIdStream>()));
    gh.lazySingleton<_i29.DeleteListItem>(() =>
        _i29.DeleteListItem(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i30.GetAllListOverviews>(() => _i30.GetAllListOverviews(
        packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i31.GetAllPacklists>(() => _i31.GetAllPacklists(
        packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i32.GetPacklist>(() =>
        _i32.GetPacklist(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.factoryParam<_i33.ItemEditCubit, _i34.ListItem, String>((
      item,
      listId,
    ) =>
        _i33.ItemEditCubit(
          item: item,
          listId: listId,
          storeListItem: gh<_i26.StoreListItem>(),
          deleteListItem: gh<_i29.DeleteListItem>(),
        ));
    gh.factoryParam<_i35.ItemSearchCubit, _i28.CurrentListCubit, dynamic>((
      currentListCubit,
      _,
    ) =>
        _i35.ItemSearchCubit(
          currentListCubit,
          gh<_i25.SearchItemByName>(),
          gh<_i26.StoreListItem>(),
        ));
    gh.factory<_i36.MylistCubit>(() => _i36.MylistCubit(
          gh<_i30.GetAllListOverviews>(),
          gh<_i20.SetCurrentPacklistId>(),
        ));
    gh.factory<_i37.PacklistBloc>(() => _i37.PacklistBloc(
          gh<_i22.GetCurrentPacklistIdStream>(),
          gh<_i32.GetPacklist>(),
          gh<_i27.CreatePacklist>(),
          gh<_i26.StoreListItem>(),
        ));
    gh.factory<_i38.CreateListCubit>(
        () => _i38.CreateListCubit(gh<_i27.CreatePacklist>()));
    return this;
  }
}

class _$RegisterConfiguration extends _i39.RegisterConfiguration {}

class _$RegisterModules extends _i39.RegisterModules {}
```
</details>

Now I add some useless injection
```
@lazySingleton
class SomeNotUsedInjection {
  SomeNotUsedInjection();
}
```

And suddenly one of the `AppConfigs` isn't injected at the top. 

<details>
<summary>Wrong GetIt injections after adding one more injection</summary>

```dart
const String _dev = 'dev';
const String _prod = 'prod';

/// ignore_for_file: unnecessary_lambdas
/// ignore_for_file: lines_longer_than_80_chars
extension GetItInjectableX on _i1.GetIt {
  /// initializes the registration of main-scope dependencies inside of [GetIt]
  Future<_i1.GetIt> init({
    String? environment,
    _i2.EnvironmentFilter? environmentFilter,
  }) async {
    final gh = _i2.GetItHelper(
      this,
      environment,
      environmentFilter,
    );
    final registerConfiguration = _$RegisterConfiguration();
    final registerModules = _$RegisterModules();
    gh.lazySingleton<_i3.UserRepository>(() => _i4.UserRepositoryImpl());
    await gh.singletonAsync<_i5.AppConfig>(
      () => registerConfiguration.appProdConfig,
      registerFor: {_prod},
      preResolve: true,
    );
    gh.lazySingleton<_i6.AppLinks>(() => registerModules.appLinks);
    gh.lazySingleton<_i7.AuthenticationClient>(
        () => _i8.AuthenticationClientImpl());
    gh.lazySingleton<_i9.GetAuthenticationStatusStream>(() =>
        _i9.GetAuthenticationStatusStream(
            authenticationClient: gh<_i7.AuthenticationClient>()));
    gh.lazySingleton<_i10.GetToken>(() =>
        _i10.GetToken(authorizationClient: gh<_i7.AuthenticationClient>()));
    gh.factory<_i11.LoginCubit>(
        () => _i11.LoginCubit(getToken: gh<_i10.GetToken>()));
    gh.singleton<_i12.QueryExecutor>(
        registerModules.dbExecutor(gh<_i5.AppConfig>()));
    await gh.singletonAsync<_i13.SharedPreferences>(
      () => registerModules.prefs,
      preResolve: true,
    );
    gh.lazySingleton<_i14.SomeNotUsedInjection>(
        () => _i14.SomeNotUsedInjection());
    gh.lazySingleton<_i14.StandalonePlaceholder>(
        () => _i14.StandalonePlaceholder());
    await gh.singletonAsync<_i5.AppConfig>(
      () => registerConfiguration.appDevConfig,
      registerFor: {_dev},
      preResolve: true,
    );
    gh.lazySingleton<_i15.GetUser>(
        () => _i15.GetUser(userRepository: gh<_i3.UserRepository>()));
    gh.singleton<_i16.PmDriftDatabase>(
        _i16.PmDriftDatabase(gh<_i12.QueryExecutor>())..initStorageInspector());
    gh.lazySingleton<_i17.PreferenceLocalDataSource>(
        () => _i17.PreferenceLocalDataSourceImpl(gh<_i13.SharedPreferences>()));
    await gh.lazySingletonAsync<_i18.PreferenceRepository>(
      () {
        final i =
            _i19.PreferenceRepositoryImpl(gh<_i17.PreferenceLocalDataSource>());
        return i.demoDefaultListInit().then((_) => i);
      },
      preResolve: true,
      dispose: (i) => i.dispose(),
    );
    gh.lazySingleton<_i20.SetCurrentPacklistId>(
        () => _i20.SetCurrentPacklistId(gh<_i18.PreferenceRepository>()));
    gh.factory<_i21.AuthenticationCubit>(() => _i21.AuthenticationCubit(
          gh<_i9.GetAuthenticationStatusStream>(),
          gh<_i15.GetUser>(),
        ));
    gh.lazySingleton<_i22.GetCurrentPacklistIdStream>(
        () => _i22.GetCurrentPacklistIdStream(gh<_i18.PreferenceRepository>()));
    gh.lazySingleton<_i14.PacklistLocalDao>(
        () => _i14.PacklistLocalDao(gh<_i16.PmDriftDatabase>()));
    gh.lazySingleton<_i23.PacklistRepository>(
        () => _i24.PacklistRepositoryImpl(gh<_i14.PacklistLocalDao>()));
    gh.factory<_i25.CreateListCubit>(
        () => _i25.CreateListCubit(gh<_i26.CreatePacklist>()));
    gh.lazySingleton<_i27.StoreListItem>(() =>
        _i27.StoreListItem(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i26.CreatePacklist>(() =>
        _i26.CreatePacklist(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.factory<_i28.CurrentListCubit>(
        () => _i28.CurrentListCubit(gh<_i22.GetCurrentPacklistIdStream>()));
    gh.lazySingleton<_i29.DeleteListItem>(() =>
        _i29.DeleteListItem(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i30.GetAllListOverviews>(() => _i30.GetAllListOverviews(
        packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i31.GetAllPacklists>(() => _i31.GetAllPacklists(
        packlistRepository: gh<_i23.PacklistRepository>()));
    gh.lazySingleton<_i32.GetPacklist>(() =>
        _i32.GetPacklist(packlistRepository: gh<_i23.PacklistRepository>()));
    gh.factoryParam<_i33.ItemEditCubit, _i34.ListItem, String>((
      item,
      listId,
    ) =>
        _i33.ItemEditCubit(
          item: item,
          listId: listId,
          storeListItem: gh<_i27.StoreListItem>(),
          deleteListItem: gh<_i29.DeleteListItem>(),
        ));
    gh.factoryParam<_i35.ItemSearchCubit, _i28.CurrentListCubit, dynamic>((
      currentListCubit,
      _,
    ) =>
        _i35.ItemSearchCubit(
          currentListCubit,
          gh<_i36.SearchItemByName>(),
          gh<_i27.StoreListItem>(),
        ));
    gh.factory<_i37.MylistCubit>(() => _i37.MylistCubit(
          gh<_i30.GetAllListOverviews>(),
          gh<_i20.SetCurrentPacklistId>(),
        ));
    gh.factory<_i38.PacklistBloc>(() => _i38.PacklistBloc(
          gh<_i22.GetCurrentPacklistIdStream>(),
          gh<_i32.GetPacklist>(),
          gh<_i26.CreatePacklist>(),
          gh<_i27.StoreListItem>(),
        ));
    gh.lazySingleton<_i36.SearchItemByName>(
        () => _i36.SearchItemByName(gh<_i23.PacklistRepository>()));
    return this;
  }
}

class _$RegisterConfiguration extends _i39.RegisterConfiguration {}

class _$RegisterModules extends _i39.RegisterModules {}
```
</details>

This obviously leads to the runtime exception:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 372 pos 7: 'instanceFactory != null': Object/factory with  type AppConfig is not registered inside GetIt. 
```

The more dependencies are added, the more false injection dependencies are added.

I will work on a reproducible example. However (if my observations are correct) this is an important bug that should be fixed.

**Comment by Milad-Akarie** [comment]
@Jozott00 I don't think the count has to do with anything, can you confirm having this in previous versions < 2.0.0?

**Comment by Jozott00** [comment]
@Milad-Akarie you are probably right. I recently updated to 2.0.0 in order to use the new `@PostConstruct` features.

**Comment by Milad-Akarie** [comment]
@Jozott00 I've been trying to reproduce the wrong order issue in the new version, can you give it a try?

**Comment by Jozott00** [comment]
@Milad-Akarie I downgraded to version ^1.5.3 and it seems to work fine with the old version

**Comment by limitless-brain** [comment]
I'm having the same issue on the latest version, I'm trying to debug it and looking for the cause of the bug.
In my case, the "IsAuthenticatedUseCase" is registered at the bottom of the container.
<details>
  <summary>injection container</summary>
```
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dio/dio.dart' as _i4;
import 'package:flutter/material.dart' as _i8;
import 'package:get_it/get_it.dart' as _i1;
import 'package:injectable/injectable.dart' as _i2;
import 'package:just_audio/just_audio.dart' as _i6;
import 'package:kamkalima/core/data/local/service/user_local_service.dart'
    as _i21;
import 'package:kamkalima/core/data/local/service/user_local_service_impl.dart'
    as _i22;
import 'package:kamkalima/core/data/local/source/user_local_source.dart'
    as _i37;
import 'package:kamkalima/core/data/local/source/user_local_source_impl.dart'
    as _i38;
import 'package:kamkalima/core/data/model/login_api_header.dart' as _i11;
import 'package:kamkalima/core/data/remote/service/user_service.dart' as _i23;
import 'package:kamkalima/core/data/remote/source/user_source.dart' as _i39;
import 'package:kamkalima/core/data/remote/source/user_source_impl.dart'
    as _i40;
import 'package:kamkalima/core/data/repository/user_repository_impl.dart'
    as _i42;
import 'package:kamkalima/core/database/app_database.dart' as _i5;
import 'package:kamkalima/core/domain/repository/user_repository.dart' as _i41;
import 'package:kamkalima/core/domain/usecase/fetch_profile_use_case.dart'
    as _i64;
import 'package:kamkalima/core/domain/usecase/is_authenticated_use_case.dart'
    as _i86;
import 'package:kamkalima/core/domain/usecase/logout_use_case.dart' as _i75;
import 'package:kamkalima/core/domain/usecase/update_first_login_use_case.dart'
    as _i82;
import 'package:kamkalima/core/domain/usecase/update_profile_use_case.dart'
    as _i83;
import 'package:kamkalima/core/domain/usecase/upload_image_use_case.dart'
    as _i84;
import 'package:kamkalima/core/presentation/bloc/notifications_listener/notifications_listener_bloc.dart'
    as _i14;
import 'package:kamkalima/core/presentation/bloc/tab_manager/tab_manager_bloc.dart'
    as _i20;
import 'package:kamkalima/core/presentation/bloc/user/user_bloc.dart' as _i85;
import 'package:kamkalima/core/utils/utils.dart' as _i25;
import 'package:kamkalima/di/app_module.dart' as _i97;
import 'package:kamkalima/features/assignments/data/remote/service/assignments_service.dart'
    as _i3;
import 'package:kamkalima/features/assignments/data/remote/source/assignments_source.dart'
    as _i48;
import 'package:kamkalima/features/assignments/data/remote/source/assignments_source_impl.dart'
    as _i49;
import 'package:kamkalima/features/assignments/data/repository/assignments_repository_impl.dart'
    as _i51;
import 'package:kamkalima/features/assignments/domain/repository/assignments_repository.dart'
    as _i50;
import 'package:kamkalima/features/assignments/domain/usecase/fetch_completed_assignments_usecase.dart'
    as _i61;
import 'package:kamkalima/features/assignments/domain/usecase/fetch_in_progress_assignments_usecase.dart'
    as _i63;
import 'package:kamkalima/features/assignments/presentation/bloc/assignments_bloc.dart'
    as _i88;
import 'package:kamkalima/features/comprehension/data/remote/service/comprehension_service.dart'
    as _i26;
import 'package:kamkalima/features/comprehension/data/remote/source/comprehension_source.dart'
    as _i52;
import 'package:kamkalima/features/comprehension/data/remote/source/comprehension_source_impl.dart'
    as _i53;
import 'package:kamkalima/features/comprehension/data/repository/comprehension_repository_impl.dart'
    as _i55;
import 'package:kamkalima/features/comprehension/domain/repository/comprehension_repository.dart'
    as _i54;
import 'package:kamkalima/features/comprehension/domain/usecase/comprehension_use_case.dart'
    as _i56;
import 'package:kamkalima/features/comprehension/presentation/bloc/comprehension/comprehension_bloc.dart'
    as _i89;
import 'package:kamkalima/features/comprehension/presentation/bloc/questions/comprehension_question_bloc.dart'
    as _i7;
import 'package:kamkalima/features/dashboard/data/remote/service/dashboard_service.dart'
    as _i27;
import 'package:kamkalima/features/dashboard/data/remote/source/dashboard_source.dart'
    as _i57;
import 'package:kamkalima/features/dashboard/data/remote/source/dashboard_source_impl.dart'
    as _i58;
import 'package:kamkalima/features/dashboard/data/repository/dashboard_repository_impl.dart'
    as _i60;
import 'package:kamkalima/features/dashboard/domain/repository/dashboard_repository.dart'
    as _i59;
import 'package:kamkalima/features/dashboard/domain/usecase/fetch_dashboard_usecase.dart'
    as _i62;
import 'package:kamkalima/features/dashboard/domain/usecase/fetch_user_usecase.dart'
    as _i65;
import 'package:kamkalima/features/dashboard/presentation/bloc/dashboard_bloc.dart'
    as _i90;
import 'package:kamkalima/features/listening/data/remote/service/listening_service.dart'
    as _i9;
import 'package:kamkalima/features/listening/data/remote/source/listening_source.dart'
    as _i28;
import 'package:kamkalima/features/listening/data/remote/source/listening_source_impl.dart'
    as _i29;
import 'package:kamkalima/features/listening/data/repository/listening_repository_impl.dart'
    as _i31;
import 'package:kamkalima/features/listening/domain/repository/listening_repository.dart'
    as _i30;
import 'package:kamkalima/features/listening/domain/usecase/listening_use_case.dart'
    as _i32;
import 'package:kamkalima/features/listening/presentation/bloc/listening/listening_bloc.dart'
    as _i71;
import 'package:kamkalima/features/login/data/remote/service/login_service.dart'
    as _i12;
import 'package:kamkalima/features/login/data/remote/source/login_source.dart'
    as _i33;
import 'package:kamkalima/features/login/data/remote/source/login_source_impl.dart'
    as _i34;
import 'package:kamkalima/features/login/data/repository/login_repository_impl.dart'
    as _i73;
import 'package:kamkalima/features/login/domain/repository/login_repository.dart'
    as _i72;
import 'package:kamkalima/features/login/domain/usecase/get_credentials_usecase.dart'
    as _i94;
import 'package:kamkalima/features/login/domain/usecase/login_usecase.dart'
    as _i74;
import 'package:kamkalima/features/login/domain/usecase/remove_credentials_usecase.dart'
    as _i80;
import 'package:kamkalima/features/login/domain/usecase/save_credentials_usecase.dart'
    as _i81;
import 'package:kamkalima/features/login/presentation/bloc/login_bloc.dart'
    as _i95;
import 'package:kamkalima/features/notifications/data/local/service/notifications_service.dart'
    as _i35;
import 'package:kamkalima/features/notifications/data/local/service/notifications_service_impl.dart'
    as _i36;
import 'package:kamkalima/features/notifications/data/local/source/notifications_data_source.dart'
    as _i76;
import 'package:kamkalima/features/notifications/data/local/source/notifications_data_source_impl.dart'
    as _i77;
import 'package:kamkalima/features/notifications/data/remote/service/notifications_service.dart'
    as _i13;
import 'package:kamkalima/features/notifications/data/remote/source/notifications_source.dart'
    as _i15;
import 'package:kamkalima/features/notifications/data/remote/source/notifications_source_impl.dart'
    as _i16;
import 'package:kamkalima/features/notifications/data/repository/notifications_repository_impl.dart'
    as _i79;
import 'package:kamkalima/features/notifications/domain/repository/notifications_repository.dart'
    as _i78;
import 'package:kamkalima/features/notifications/domain/usecase/delete_all_notifications_use_case.dart'
    as _i91;
import 'package:kamkalima/features/notifications/domain/usecase/delete_notification_use_case.dart'
    as _i92;
import 'package:kamkalima/features/notifications/domain/usecase/disable_notifications_interest_use_case.dart'
    as _i70;
import 'package:kamkalima/features/notifications/domain/usecase/enable_notifications_interest_use_case.dart'
    as _i69;
import 'package:kamkalima/features/notifications/domain/usecase/fetch_notifications_enabled_interest_use_case.dart'
    as _i68;
import 'package:kamkalima/features/notifications/domain/usecase/fetch_notifications_interest_use_case.dart'
    as _i67;
import 'package:kamkalima/features/notifications/domain/usecase/fetch_notifications_use_case.dart'
    as _i93;
import 'package:kamkalima/features/notifications/presentation/bloc/notifications/notifications_bloc.dart'
    as _i96;
import 'package:kamkalima/features/notifications/presentation/bloc/settings/notifications_settings_bloc.dart'
    as _i66;
import 'package:kamkalima/features/writing/data/remote/service/writing_service.dart'
    as _i24;
import 'package:kamkalima/features/writing/data/remote/source/writing_source.dart'
    as _i43;
import 'package:kamkalima/features/writing/data/remote/source/writing_source_impl.dart'
    as _i44;
import 'package:kamkalima/features/writing/data/repository/writing_repository_impl.dart'
    as _i46;
import 'package:kamkalima/features/writing/domain/repository/writing_repository.dart'
    as _i45;
import 'package:kamkalima/features/writing/domain/usecase/writing_use_case.dart'
    as _i47;
import 'package:kamkalima/features/writing/presentation/bloc/writing_bloc.dart'
    as _i87;
import 'package:logger/logger.dart' as _i10;
import 'package:package_info_plus/package_info_plus.dart' as _i17;
import 'package:pusher_beams/pusher_beams.dart' as _i18;
import 'package:shared_preferences/shared_preferences.dart' as _i19;

const String _prod = 'prod';
const String _test = 'test';
const String _dev = 'dev';

/// ignore_for_file: unnecessary_lambdas
/// ignore_for_file: lines_longer_than_80_chars
extension GetItInjectableX on _i1.GetIt {
  /// initializes the registration of main-scope dependencies inside of [GetIt]
  Future<_i1.GetIt> init({
    String? environment,
    _i2.EnvironmentFilter? environmentFilter,
  }) async {
    final gh = _i2.GetItHelper(
      this,
      environment,
      environmentFilter,
    );
    final appModule = _$AppModule();
    gh.factory<_i3.AssignmentsRemoteService>(
        () => _i3.AssignmentsRemoteService(gh<_i4.Dio>()));
    gh.lazySingleton<_i5.AppDatabase>(() => appModule.appDatabase);
    gh.lazySingleton<_i6.AudioPlayer>(() => appModule.audioPlayer);
    gh.factory<_i7.ComprehensionQuestionBloc>(
        () => _i7.ComprehensionQuestionBloc());
    gh.lazySingleton<_i4.Dio>(
      () => appModule.loginDio,
      instanceName: 'LoginDio',
    );
    gh.lazySingleton<_i4.Dio>(() => appModule.apiDio);
    gh.singleton<_i8.GlobalKey<_i8.ScaffoldMessengerState>>(
        appModule.scaffoldMessengerKey);
    gh.singleton<_i8.GlobalKey<_i8.NavigatorState>>(appModule.navigatorKey);
    gh.factory<_i9.ListeningService>(() => _i9.ListeningService(gh<_i4.Dio>()));
    gh.singleton<_i10.Logger>(appModule.logger);
    await gh.factoryAsync<_i11.LoginApiHeaders>(
      () => appModule.loginApiHeaders,
      preResolve: true,
    );
    gh.factory<_i12.LoginService>(
        () => _i12.LoginService(gh<_i4.Dio>(instanceName: 'LoginDio')));
    gh.factory<_i13.NotificationRemoteService>(
        () => _i13.NotificationRemoteService(gh<_i4.Dio>()));
    gh.singleton<_i14.NotificationsListenerBloc>(
        _i14.NotificationsListenerBloc());
    gh.factory<_i15.NotificationsRemoteDataSource>(() =>
        _i16.NotificationsRemoteDataSourceImpl(
            gh<_i13.NotificationRemoteService>()));
    await gh.factoryAsync<_i17.PackageInfo>(
      () => appModule.packageInfo,
      preResolve: true,
    );
    gh.singleton<_i18.PusherBeams>(appModule.pusherBeams);
    await gh.factoryAsync<_i19.SharedPreferences>(
      () => appModule.prefs,
      preResolve: true,
    );
    gh.singleton<String>(
      appModule.apiDevBaseUrl,
      instanceName: 'base_url',
      registerFor: {_dev},
    );
    gh.singleton<String>(
      appModule.apiStagingBaseUrl,
      instanceName: 'base_url',
      registerFor: {_test},
    );
    gh.singleton<String>(
      appModule.apiBaseUrl,
      instanceName: 'base_url',
      registerFor: {_prod},
    );
    gh.factory<_i20.TabManagerBloc>(() => _i20.TabManagerBloc());
    gh.factory<_i5.UserDao>(() => _i5.UserDao(gh<_i5.AppDatabase>()));
    gh.factory<_i21.UserLocalService>(() => _i22.UserLocalServiceImpl(
          gh<_i5.UserDao>(),
          gh<_i19.SharedPreferences>(),
        ));
    gh.factory<_i23.UserRemoteService>(
        () => _i23.UserRemoteService(gh<_i4.Dio>()));
    gh.factory<_i24.WritingService>(() => _i24.WritingService(gh<_i4.Dio>()));
    gh.lazySingleton<_i25.ApiHeaderGetter>(() => appModule.apiHeaderGetter);
    gh.factory<_i26.ComprehensionService>(
        () => _i26.ComprehensionService(gh<_i4.Dio>()));
    gh.factory<_i27.DashboardService>(
        () => _i27.DashboardService(gh<_i4.Dio>()));
    gh.factory<_i28.ListeningRemoteDataSource>(
        () => _i29.ListeningRemoteDataSourceImpl(gh<_i9.ListeningService>()));
    gh.factory<_i30.ListeningRepository>(() =>
        _i31.ListeningRepositoryImpl(gh<_i28.ListeningRemoteDataSource>()));
    gh.factory<_i32.ListeningUseCase>(
        () => _i32.ListeningUseCase(gh<_i30.ListeningRepository>()));
    gh.lazySingleton<_i33.LoginRemoteDataSource>(
        () => _i34.LoginRemoteDataSourceImpl(gh<_i12.LoginService>()));
    gh.factory<_i35.NotificationsLocalService>(
        () => _i36.NotificationsLocalServiceImpl(gh<_i19.SharedPreferences>()));
    gh.factory<_i37.UserLocalDataSource>(() => _i38.UserLocalDataSourceImpl(
          gh<_i21.UserLocalService>(),
          gh<_i19.SharedPreferences>(),
        ));
    gh.factory<_i39.UserRemoteDataSource>(
        () => _i40.UserRemoteDataSourceImpl(gh<_i23.UserRemoteService>()));
    gh.factory<_i41.UserRepository>(() => _i42.UserRepositoryImpl(
          gh<_i39.UserRemoteDataSource>(),
          gh<_i37.UserLocalDataSource>(),
        ));
    gh.factory<_i43.WritingRemoteDataSource>(
        () => _i44.WritingRemoteDataSourceImpl(gh<_i24.WritingService>()));
    gh.factory<_i45.WritingRepository>(
        () => _i46.WritingRepositoryImpl(gh<_i43.WritingRemoteDataSource>()));
    gh.factory<_i47.WritingUseCase>(
        () => _i47.WritingUseCase(gh<_i45.WritingRepository>()));
    gh.factory<_i48.AssignmentsRemoteDataSource>(() =>
        _i49.AssignmentsRemoteDataSourceImpl(
            gh<_i3.AssignmentsRemoteService>()));
    gh.factory<_i50.AssignmentsRepository>(() =>
        _i51.AssignmentsRepositoryImpl(gh<_i48.AssignmentsRemoteDataSource>()));
    gh.factory<_i52.ComprehensionRemoteDataSource>(() =>
        _i53.ComprehensionRemoteDataSourceImpl(
            gh<_i26.ComprehensionService>()));
    gh.factory<_i54.ComprehensionRepository>(() =>
        _i55.ComprehensionRepositoryImpl(
            gh<_i52.ComprehensionRemoteDataSource>()));
    gh.factory<_i56.ComprehensionUseCase>(
        () => _i56.ComprehensionUseCase(gh<_i54.ComprehensionRepository>()));
    gh.factory<_i57.DashboardRemoteDataSource>(
        () => _i58.DashboardRemoteDataSourceImpl(gh<_i27.DashboardService>()));
    gh.factory<_i59.DashboardRepository>(() => _i60.DashboardRepositoryImpl(
          gh<_i57.DashboardRemoteDataSource>(),
          gh<_i37.UserLocalDataSource>(),
        ));
    gh.factory<_i61.FetchCompletedAssignmentsUseCase>(() =>
        _i61.FetchCompletedAssignmentsUseCase(
            gh<_i50.AssignmentsRepository>()));
    gh.factory<_i62.FetchDashboardUseCase>(
        () => _i62.FetchDashboardUseCase(gh<_i59.DashboardRepository>()));
    gh.factory<_i63.FetchInProgressAssignmentsUseCase>(() =>
        _i63.FetchInProgressAssignmentsUseCase(
            gh<_i50.AssignmentsRepository>()));
    gh.factory<_i64.FetchProfileUseCase>(
        () => _i64.FetchProfileUseCase(gh<_i41.UserRepository>()));
    gh.factory<_i65.FetchUserUseCase>(
        () => _i65.FetchUserUseCase(gh<_i59.DashboardRepository>()));
    gh.factory<_i66.NotificationsSettingsBloc>(
        () => _i66.NotificationsSettingsBloc(
              gh<_i67.FetchNotificationsInterestUseCase>(),
              gh<_i68.FetchNotificationsEnabledInterestUseCase>(),
              gh<_i69.EnableNotificationsInterestUseCase>(),
              gh<_i70.DisableNotificationsInterestUseCase>(),
            ));
    gh.factory<_i71.ListeningBloc>(
        () => _i71.ListeningBloc(gh<_i32.ListeningUseCase>()));
    gh.lazySingleton<_i72.LoginRepository>(() => _i73.LoginRepositoryImpl(
          gh<_i33.LoginRemoteDataSource>(),
          gh<_i37.UserLocalDataSource>(),
          gh<_i19.SharedPreferences>(),
          gh<_i4.Dio>(),
          gh<_i18.PusherBeams>(),
          gh<_i25.ApiHeaderGetter>(),
        ));
    gh.factory<_i74.LoginUseCase>(
        () => _i74.LoginUseCase(gh<_i72.LoginRepository>()));
    gh.factory<_i75.LogoutUseCase>(
        () => _i75.LogoutUseCase(gh<_i41.UserRepository>()));
    gh.factory<_i76.NotificationsLocalDataSource>(() =>
        _i77.NotificationsLocalDataSourceImpl(
            gh<_i35.NotificationsLocalService>()));
    gh.factory<_i78.NotificationsRepository>(
        () => _i79.NotificationsRepositoryImpl(
              gh<_i15.NotificationsRemoteDataSource>(),
              gh<_i76.NotificationsLocalDataSource>(),
              gh<_i18.PusherBeams>(),
            ));
    gh.factory<_i80.RemoveCredentialsUseCase>(
        () => _i80.RemoveCredentialsUseCase(gh<_i72.LoginRepository>()));
    gh.factory<_i81.SaveCredentialsUseCase>(
        () => _i81.SaveCredentialsUseCase(gh<_i72.LoginRepository>()));
    gh.factory<_i82.UpdateFirstLoginUseCase>(
        () => _i82.UpdateFirstLoginUseCase(gh<_i41.UserRepository>()));
    gh.factory<_i83.UpdateProfileUseCase>(
        () => _i83.UpdateProfileUseCase(gh<_i41.UserRepository>()));
    gh.factory<_i84.UploadImageUseCase>(
        () => _i84.UploadImageUseCase(gh<_i41.UserRepository>()));
    gh.singleton<_i85.UserBloc>(_i85.UserBloc(
      gh<_i86.IsAuthenticatedUseCase>(),
      gh<_i64.FetchProfileUseCase>(),
      gh<_i84.UploadImageUseCase>(),
      gh<_i83.UpdateProfileUseCase>(),
      gh<_i75.LogoutUseCase>(),
      gh<_i82.UpdateFirstLoginUseCase>(),
    ));
    gh.factory<_i87.WritingBloc>(() => _i87.WritingBloc(
          gh<_i47.WritingUseCase>(),
          gh<_i84.UploadImageUseCase>(),
        ));
    gh.factory<_i88.AssignmentsBloc>(() => _i88.AssignmentsBloc(
          gh<_i63.FetchInProgressAssignmentsUseCase>(),
          gh<_i61.FetchCompletedAssignmentsUseCase>(),
        ));
    gh.factory<_i89.ComprehensionBloc>(
        () => _i89.ComprehensionBloc(gh<_i56.ComprehensionUseCase>()));
    gh.factory<_i90.DashboardBloc>(() => _i90.DashboardBloc(
          gh<_i62.FetchDashboardUseCase>(),
          gh<_i65.FetchUserUseCase>(),
          gh<_i19.SharedPreferences>(),
        ));
    gh.factory<_i91.DeleteAllNotificationsUseCase>(() =>
        _i91.DeleteAllNotificationsUseCase(gh<_i78.NotificationsRepository>()));
    gh.factory<_i92.DeleteNotificationUseCase>(() =>
        _i92.DeleteNotificationUseCase(gh<_i78.NotificationsRepository>()));
    gh.factory<_i70.DisableNotificationsInterestUseCase>(() =>
        _i70.DisableNotificationsInterestUseCase(
            gh<_i78.NotificationsRepository>()));
    gh.factory<_i69.EnableNotificationsInterestUseCase>(() =>
        _i69.EnableNotificationsInterestUseCase(
            gh<_i78.NotificationsRepository>()));
    gh.factory<_i68.FetchNotificationsEnabledInterestUseCase>(() =>
        _i68.FetchNotificationsEnabledInterestUseCase(
            gh<_i78.NotificationsRepository>()));
    gh.factory<_i67.FetchNotificationsInterestUseCase>(() =>
        _i67.FetchNotificationsInterestUseCase(
            gh<_i78.NotificationsRepository>()));
    gh.factory<_i93.FetchNotificationsUseCase>(() =>
        _i93.FetchNotificationsUseCase(gh<_i78.NotificationsRepository>()));
    gh.factory<_i94.GetCredentialUseCase>(
        () => _i94.GetCredentialUseCase(gh<_i72.LoginRepository>()));
    gh.factory<_i95.LoginBloc>(() => _i95.LoginBloc(
          gh<_i74.LoginUseCase>(),
          gh<_i94.GetCredentialUseCase>(),
          gh<_i81.SaveCredentialsUseCase>(),
          gh<_i80.RemoveCredentialsUseCase>(),
          gh<_i85.UserBloc>(),
        ));
    gh.factory<_i96.NotificationsBloc>(() => _i96.NotificationsBloc(
          gh<_i93.FetchNotificationsUseCase>(),
          gh<_i92.DeleteNotificationUseCase>(),
          gh<_i91.DeleteAllNotificationsUseCase>(),
        ));
    gh.factory<_i86.IsAuthenticatedUseCase>(
        () => _i86.IsAuthenticatedUseCase(gh<_i41.UserRepository>()));
    return this;
  }
}

class _$AppModule extends _i97.AppModule {}

```
</details>

**Comment by Milad-Akarie** [comment]
@Jozott00 @limitless-brain is any of you using barrel files as in exporting a dependency?

**Comment by Jozott00** [comment]
No, I do not have barrel files

**Comment by Milad-Akarie** [comment]
@Jozott00 @limitless-brain I just pushed a fix to a barrel files related issue `injectable_generator: 2.1.1 `
can you check if it fixes the registration order issue?

**Comment by Jozott00** [comment]
I found a minimal reproducible example. And its actually again the 33 dependency mark ^^

By deleting only one of the dummy dependency it works.

```dart
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:injectable_issue/injection_issue.config.dart';

final sl = GetIt.instance;

void main() async {
  await configureInjections();
}

@InjectableInit()
Future<void> configureInjections() async => await sl.init(environment: "prod");

@module
abstract class EnvConf {

  @dev
  @preResolve
  @singleton
  Future<AppConf> confDev() async => AppConf();

  @prod
  @preResolve
  @singleton
  Future<AppConf> confProd() async => AppConf();
}

class AppConf {}

@singleton
class Dep0 {
  Dep0(AppConf conf) {}
}

@singleton class Dep1 { }
@singleton class Dep2 { }
@singleton class Dep3 { }
@singleton class Dep4 { }
@singleton class Dep5 { }
@singleton class Dep6 { }
@singleton class Dep7 { }
@singleton class Dep8 { }
@singleton class Dep9 { }
@singleton class Dep10 { }
@singleton class Dep11 { }
@singleton class Dep12 { }
@singleton class Dep13 { }
@singleton class Dep14 { }
@singleton class Dep15 { }
@singleton class Dep16 { }
@singleton class Dep17 { }
@singleton class Dep18 { }
@singleton class Dep19 { }
@singleton class Dep20 { }
@singleton class Dep21 { }
@singleton class Dep22 { }
@singleton class Dep23 { }
@singleton class Dep24 { }
@singleton class Dep25 { }
@singleton class Dep26 { }
@singleton class Dep27 { }
@singleton class Dep28 { }
@singleton class Dep29 { }
@singleton class Dep30 { }
@singleton class Dep31 { }
```

<details>
<summary>Generated Code: </summary>

```
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:get_it/get_it.dart' as _i1;
import 'package:injectable/injectable.dart' as _i2;
import 'package:injectable_issue/injection_issue.dart' as _i3;

const String _dev = 'dev';
const String _prod = 'prod';

/// ignore_for_file: unnecessary_lambdas
/// ignore_for_file: lines_longer_than_80_chars
extension GetItInjectableX on _i1.GetIt {
  /// initializes the registration of main-scope dependencies inside of [GetIt]
  Future<_i1.GetIt> init({
    String? environment,
    _i2.EnvironmentFilter? environmentFilter,
  }) async {
    final gh = _i2.GetItHelper(
      this,
      environment,
      environmentFilter,
    );
    final envConf = _$EnvConf();
    gh.singleton<_i3.Dep17>(_i3.Dep17());
    await gh.singletonAsync<_i3.AppConf>(
      () => envConf.confDev(),
      registerFor: {_dev},
      preResolve: true,
    );
    gh.singleton<_i3.Dep0>(_i3.Dep0(gh<_i3.AppConf>()));
    gh.singleton<_i3.Dep1>(_i3.Dep1());
    gh.singleton<_i3.Dep10>(_i3.Dep10());
    gh.singleton<_i3.Dep11>(_i3.Dep11());
    gh.singleton<_i3.Dep12>(_i3.Dep12());
    gh.singleton<_i3.Dep13>(_i3.Dep13());
    gh.singleton<_i3.Dep14>(_i3.Dep14());
    gh.singleton<_i3.Dep15>(_i3.Dep15());
    gh.singleton<_i3.Dep16>(_i3.Dep16());
    await gh.singletonAsync<_i3.AppConf>(
      () => envConf.confProd(),
      registerFor: {_prod},
      preResolve: true,
    );
    gh.singleton<_i3.Dep18>(_i3.Dep18());
    gh.singleton<_i3.Dep19>(_i3.Dep19());
    gh.singleton<_i3.Dep2>(_i3.Dep2());
    gh.singleton<_i3.Dep20>(_i3.Dep20());
    gh.singleton<_i3.Dep21>(_i3.Dep21());
    gh.singleton<_i3.Dep22>(_i3.Dep22());
    gh.singleton<_i3.Dep23>(_i3.Dep23());
    gh.singleton<_i3.Dep24>(_i3.Dep24());
    gh.singleton<_i3.Dep25>(_i3.Dep25());
    gh.singleton<_i3.Dep9>(_i3.Dep9());
    gh.singleton<_i3.Dep27>(_i3.Dep27());
    gh.singleton<_i3.Dep28>(_i3.Dep28());
    gh.singleton<_i3.Dep29>(_i3.Dep29());
    gh.singleton<_i3.Dep3>(_i3.Dep3());
    gh.singleton<_i3.Dep30>(_i3.Dep30());
    gh.singleton<_i3.Dep31>(_i3.Dep31());
    gh.singleton<_i3.Dep4>(_i3.Dep4());
    gh.singleton<_i3.Dep5>(_i3.Dep5());
    gh.singleton<_i3.Dep6>(_i3.Dep6());
    gh.singleton<_i3.Dep7>(_i3.Dep7());
    gh.singleton<_i3.Dep8>(_i3.Dep8());
    gh.singleton<_i3.Dep26>(_i3.Dep26());
    return this;
  }
}

class _$EnvConf extends _i3.EnvConf {}
```
</details>

**Comment by Jozott00** [comment]
Update: here is a more minimal example
```dart

import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:injectable_issue/injection_issue.config.dart';

final sl = GetIt.instance;

void main() async {
  await configureInjections();
}

@InjectableInit()
Future<void> configureInjections() async => sl.init();

@singleton
class AppConf {}

@singleton
class Dep0 {
  Dep0(AppConf conf) {}
}

@singleton class Dep1 { }
@singleton class Dep2 { }
@singleton class Dep3 { }
@singleton class Dep4 { }
@singleton class Dep5 { }
@singleton class Dep6 { }
@singleton class Dep7 { }
@singleton class Dep8 { }
@singleton class Dep9 { }
@singleton class Dep10 { }
@singleton class Dep11 { }
@singleton class Dep12 { }
@singleton class Dep13 { }
@singleton class Dep14 { }
@singleton class Dep15 { }
@singleton class Dep16 { }
@singleton class Dep17 { }
@singleton class Dep18 { }
@singleton class Dep19 { }
@singleton class Dep20 { }
@singleton class Dep21 { }
@singleton class Dep22 { }
@singleton class Dep23 { }
@singleton class Dep24 { }
@singleton class Dep25 { }
@singleton class Dep26 { }
@singleton class Dep27 { }
@singleton class Dep28 { }
@singleton class Dep29 { }
@singleton class Dep30 { }
@singleton class Dep31 { }
@singleton class Dep32 { }
```

**Comment by Jozott00** [comment]
@Milad-Akarie Just upgraded to generator version 2.1.1. The minimal example of the previous post still does not work

**Comment by Milad-Akarie** [comment]
@Jozott00 Thank you, all I needed was a reproducible example. I think I got this fixed but I didn't check the count, I still don't think it has anything to do with this. anyways the issue had to do with the order sort method I got from a PR.
Please check version 2.1.2 and confirm if everything works as expected.

**Comment by Jozott00** [comment]
@Milad-Akarie Yes, I can confirm that the issue is solved for my project! Great job and thanks for this really fast fix!!
